config/routes.rb
Brain::Application.routes.draw do

 
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  resources :games do
    collection do
      get 'ajax'
    end
  end

  resources :interestings
  
  resources :quests do
    resources :steps
  end
  
  resources :steps do
    resources :variants
    resources :comments
  end
  

   root :to => 'games#index'

  
end

app/views/shared/_nemanic.erb
<%= "Виберіть інший квест" %> </br>
<%=link_to "Вернутись назад", root_path%>
<%=  render "shared/rightebar" %>

app/views/shared/_nexist.html.erb
<h1> Виберіть інший квест </h1>
<%=  link_to "На головну", root_path %>
<%= render "shared/rightebar" %>

app/views/shared/_rightebar.html.erb
<%= content_for :rightebar do %>
<% if @interesting.present?%>
  <%= @interesting.body %>
<% else %> 
правий кусок і має показувати цікавинки! Справити це негайно!
   <%end%>

<% end  %>  

app/views/shared/_sidebar.html.erb
<%= content_for :sidebar do %>
  <% @quests.each do |quest| %>
    <h3><%=link_to quest.name, quest_path(quest)%></h3>  
    
    <%= link_to 'Edit', edit_quest_path(quest) %> | <%= link_to 'Destroy', quest, confirm: 'Are you sure?', method: :delete %>

  <% end %>
<% end  %>  

app/views/shared/_sidebar_content.html.erb
<%= content_for :sidebar do %>
  <h3><%=@quest.name%> 
    <p> <%= link_to 'Edit', edit_quest_path(@quest) %> |
      <%= link_to 'Back', quests_path %> |
      <%= link_to 'Destroy', @quest, confirm: 'Are you sure?', method: :delete %></p>
  </h3> 

  <ul class="steps">
    <%@quest.steps.each do |s|%>
      <li class="<%= params[:step_id] == s.id.to_s ? "selected" : "" %>">

        <%= link_to s.title, edit_quest_step_path(@quest, s), :title => "edit" %>
        <% if params[:step_id] == s.id.to_s || params[:controller] == "steps" && params[:id] == s.id.to_s %>
          &larr; вибраний
        <%end%>
      <ul>
        <%s.variants.each do |v|%>
          <li><%= link_to v.body, edit_step_variant_path(s, v)%> &rarr; <%=v.next_step.title if v.next_step%></li>
        <%end%>
        <li><%=link_to "додати варіант", new_step_variant_path(s)%></li>
      </ul>
    </li>
  <%end%>
</ul>

<%= link_to 'Додати крок', new_quest_step_path(@quest) %>
<% end  %>  