config/routes.rb
Brain::Application.routes.draw do

 
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  resources :games do
    collection do
      get 'ajax'
    end
  end

  resources :interestings
  
  resources :quests do
    resources :steps
  end
  
  resources :steps do
    resources :variants
    resources :comments
  end
  

   root :to => 'games#index'

  
end

app/models/step.rb
# -*- encoding : utf-8 -*-
class Step < ActiveRecord::Base
  has_many :variants, :dependent => :destroy

  belongs_to :quest
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates :description, :quest_id, :title, :presence => true
  #validates :title, :uniqueness => true
end

app/controllers/steps_controller.rb
# -*- encoding : utf-8 -*-
class StepsController < ApplicationController
  before_filter :get_quest
  # GET /steps
  # GET /steps.json
  def index
  
    @steps = @quest.steps
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = Step.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
   
    @step = Step.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /steps/1/edit
  def edit
    @step = Step.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
  
    @step = @quest.steps.new(params[:step])

    
   
      if @step.save
        redirect_to (quest_path(@quest)), notice: 'Step was successfully created.'

      else
        render action: "new" 
      end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
   
    @step = Step.find(params[:id])

    if @step.update_attributes(params[:step])
        redirect_to (quest_path(@quest)), notice: 'Step was successfully updated.'

      else
         render action: "edit" 
      end
    
    
   
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = Step.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to quest_steps_url(@quest) }
      format.json { head :ok }
    end
  end
  
private

  def get_quest
        @quest = Quest.find(params[:quest_id])
  end
end

app/helpers/steps_helper.rb
# -*- encoding : utf-8 -*-
module StepsHelper
end

app/views/steps/_form.html.erb
<%= form_for [@quest,@step] do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "40x5"%>
  </div>
  <div class="field">
    <%= f.label :result %><br />
    <%= f.text_field :result, :size => "35x5" %>
  </div>
  <div class="field">
    <%= f.label :video %><br />
    <%= f.text_area :video, :size => "40x5" %>
  </div>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title, :size => "40x5" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>
<%=  render "shared/sidebar_content" %> 
<%= render 'form' %>

<%= link_to 'Show', [@quest,@step] %> |
<%= link_to 'Back', quest_steps_path %>|
<%= link_to 'Delete step', quest_step_path(@quest, @step), confirm: 'Are you sure?', method: :delete  %>

app/views/steps/index.html.erb
<h1>Кроки</h1>
<%=  render "shared/sidebar_content" %> 
<%=link_to 'Назад', quests_path %>

app/views/steps/new.html.erb
<h1>New step</h1>
<%=  render "shared/sidebar_content" %> 
<%= render 'form' %>

<%= link_to 'Back', quest_steps_path %>

app/views/steps/show.html.erb
<%=  render "shared/sidebar_content" %> 

 <%= image_tag @step.photo.url(:medium) if @step.photo.exists? %>

<p>
  <b>Description:</b>
  <%= @step.description %>
</p>

<p>
  <b>Result:</b>
  <%= @step.result %>
</p>

<p>
  <b>Video:</b>
  <%= @step.video %>
</p>

<p>
  <b>Quest:</b>
  <%= @step.quest_id %>
</p>

<p>
  <b>Title:</b>
  <%= @step.title %>
</p>


<%= link_to 'Edit', edit_quest_step_path(@quest, @step) %> |
<%= link_to 'Back', quest_steps_path(@quest) %> |
<%= link_to 'Додати варіант', new_step_variant_path(@step) %>|