config/routes.rb
Brain::Application.routes.draw do

 
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  resources :games do
    collection do
      get 'ajax'
    end
  end

  resources :interestings
  
  resources :quests do
    resources :steps
  end
  
  resources :steps do
    resources :variants
    resources :comments
  end
  

   root :to => 'games#index'

  
end

app/models/interesting.rb
class Interesting < ActiveRecord::Base
   validates :body, :presence => true
end

app/controllers/interestings_controller.rb
class InterestingsController < ApplicationController
  # GET /interestings
  # GET /interestings.json
  def index
    @interestings = Interesting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interestings }
    end
  end

  # GET /interestings/1
  # GET /interestings/1.json
  def show
    @interesting = Interesting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interesting }
    end
  end

  # GET /interestings/new
  # GET /interestings/new.json
  def new
    @interesting = Interesting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interesting }
    end
  end

  # GET /interestings/1/edit
  def edit
    @interesting = Interesting.find(params[:id])
  end

  # POST /interestings
  # POST /interestings.json
  def create
    @interesting = Interesting.new(params[:interesting])

    respond_to do |format|
      if @interesting.save
        format.html { redirect_to @interesting, notice: 'Interesting was successfully created.' }
        format.json { render json: @interesting, status: :created, location: @interesting }
      else
        format.html { render action: "new" }
        format.json { render json: @interesting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interestings/1
  # PUT /interestings/1.json
  def update
    @interesting = Interesting.find(params[:id])

    respond_to do |format|
      if @interesting.update_attributes(params[:interesting])
        format.html { redirect_to @interesting, notice: 'Interesting was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @interesting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interestings/1
  # DELETE /interestings/1.json
  def destroy
    @interesting = Interesting.find(params[:id])
    @interesting.destroy

    respond_to do |format|
      format.html { redirect_to interestings_url }
      format.json { head :ok }
    end
  end
end

app/helpers/interestings_helper.rb
module InterestingsHelper
end

app/views/interestings/_form.html.erb
<%= form_for(@interesting) do |f| %>
  <% if @interesting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interesting.errors.count, "error") %> prohibited this interesting from being saved:</h2>

      <ul>
      <% @interesting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interestings/edit.html.erb
<h1>Editing interesting</h1>

<%= render 'form' %>

<%= link_to 'Show', @interesting %> |
<%= link_to 'Back', interestings_path %>

app/views/interestings/index.html.erb
<h1>Listing interestings</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interestings.each do |interesting| %>
  <td> <%=simple_format truncate(interesting.body, :length=>10, :separator=>" ", :omission => "... (#{link_to 'більше тексту', interesting_path(interesting)})")%> </td>
  <tr>
    <td><%= link_to 'Edit', edit_interesting_path(interesting) %> |
    <%= link_to 'Destroy', interesting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interesting', new_interesting_path %>

app/views/interestings/new.html.erb
<h1>нова цікавинка</h1>

<%= render 'form' %>

<%= link_to 'Back', interestings_path %>

app/views/interestings/show.html.erb
<p id="notice"><%= notice %></p>
<div> <%= @interesting.body %> </div>

<%= link_to 'Edit', edit_interesting_path(@interesting) %> |
<%= link_to 'Back', interestings_path %>